apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', "Success! > /output/success.txt"]
    volumeMounts:
      - name: my-volume
        mountPath: /output
  volumes:
  - name: my-volume
    hostPath:
        path: /var/data