apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
      - name: my-volume
        mountPath: /output
  volumes:
    - name: my-volume
      hostPath:
        path: /tmp
